name: Run formatters and linters
run-name: ${{ forgejo.actor }} is running formatters and linters
on:
  push:
    branches:
      - main
      - develop
  pull_request:
jobs:
  checks:
    runs-on: nix
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: treefmt
        run: nix develop -c nix fmt -- --fail-on-change
      - name: clippy
        run: nix develop -c cargo clippy --all-features --all-targets -- -D warnings
